### ISSUE TITLE
Does the code still work?

### ISSUE THREAD

**Issue by AboutSange** [DrewStewart7/CSGO-Market-Tracker#1]
I filled in the auth(with scid), secret, clientID parameters in config.json, and cookiestring.txt, and test `post https://skinport.com/api/cart/add` get error:

![image](https://github.com/DrewStewart7/CSGO-Market-Tracker/assets/27603447/b86f2af1-064b-46b4-9fbe-2405e1bde278)

Does cloudflare WAF block it? Does the code still work?

**Comment by DrewStewart7** [comment]
Hello and thank you for showing interest in the project.

I'll look into this issue today. I haven't updated/used this program in a while and it's possible/likely that SkinPort updated their endpoints. I'll let you know what I find!

**Comment by DrewStewart7** [comment]
Ok, yes I remember now. Cloudflare does block the add to cart endpoint through the use of a an obscure csrf system. I think it's possible to get past, but even at that there's even tougher blocking on the purchase/checkout flow. I recommend using the notifier instead of main.py, as Skinport prides themselves on being bot free, and they have the defense to back up that claim.

**Comment by AboutSange** [comment]
Thank you for getting back to me.
I find the source of param `_csrf` for `POST https://skinport.com/api/cart/add` is `csrf` of response body from `GET https://skinport.com/api/data`,
But I do not know how to use the browser cookies to pass cloudflare waf, do you have any ideas?

**Comment by DrewStewart7** [comment]
Hi, I came to the same conclusion. WAF is what prevented me from making this a full-blown item sniper haha. So no, unfortunately I do not know how to bypass it. If you find anything please let me know.

**Comment by AboutSange** [comment]
Well, I don't know any more, thanks
